server:
  port: 8080

spring:
  application:
    name: taskforge 
  datasource:
    url: jdbc:postgresql://database:5432/taskforge_db
    username: admin
    password: admin
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password
